default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: william_fish_development
test:
  <<: *default
  database: william_fish_test
production:
  <<: *default
  database: william_fish_production
  username: william_fish
  password: <%= ENV['WILLIAM_FISH_DATABASE_PASSWORD'] %>
