# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1f9d0086561d6d2dcc08805d494ae9ec59ff94ab5a9c76070ccb3c690560d95127911d5f8e9ec4774102a0cf00a28d28660c5a2be692aebebe09fea8e22e9c7

test:
  secret_key_base: 902ca1d57587b4ff52aa059f7ce7efcca4538b10c295b065733a154dd543879d6210aaffa6db11966332eb55a345eab6307bc694c7345296f9244baafb1d8ab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
